export class TAApplication {
    public id: number;
    public advisorTeamName: string;
    public numberOfAdvisors: number;
    public priorFirmName: string;
    public submitterUserId: number;
    public createDate: Date;
    public lastModify: Date;
    public isActive: boolean;
    public aIsUITCashValue: string;
    public aIsUITCashPercentage: number;
    public advisoryAUMValue: string;
    public advisoryAUMpercentage: number;
    public brokerageAUMValue: string;
    public brokerageAUMPercentage: number;
    public eaum: string;
    public fixedAnnuitiesValue: string;
    public fixedAnnuitiesPercentage: number;
    public fixedIncomeValue: string;
    public fixedIncomePercentage: number;
    public gdcroa: number;
    public generalSecuritiesValue: string;
    public generalSecuritiesPercentage: number;
    public mFsCustodiedValue: string;
    public mFsCustodiedPercentage: number;
    public mFsDirectValue: string;
    public mFsDirectPercentage: number;
    public priorFirmType: string;
    public t12AdvisoryGDC: string;
    public t12BrokerageGDC: string;
    public vaum: string;
    public variableAnnuitiesValue: string;
    public variableAnnuitiesPercentage: number;
    public ramp: number
}
